apiVersion: v1
kind: Service
metadata:
  labels:
    app: hpa-deployment
  name: php-apache
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 80
  selector:
    app: hpa-deployment
  type: ClusterIP

